on: 
  push:
    branches:
    - master
name: Release
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm ci
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: npm
        args: ci
    - name: semantic-release
      uses: docker://timbru31/node-alpine-git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        entrypoint: npx
        args: semantic-release
