on: pull_request
name: Test
jobs:
  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: github.event.action == 'synchronize'
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run routes:lint
      - run: npx standard
      - run: npm run test:ci
