on: repository_dispatch
name: Update on demand
jobs:
  npmCi:
    name: Update on demand
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm ci
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: npm
        args: ci
    - name: clear routes
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: rm
        args: -rf openapi/*/operations/* cache
    - name: update GHE routes
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: bin/octokit-rest-routes.js
        args: update --ghe
    - name: update .com routes
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: bin/octokit-rest-routes.js
        args: update
    - name: config git email
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: git
        args: config --global user.email 'octokitbot@martynus.net'
    - name: config git name
      uses: docker://timbru31/node-alpine-git
      with:
        entrypoint: git
        args: config --global user.name 'OctokitBot'
    - name: routes update pull request
      uses: docker://timbru31/node-alpine-git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: bin/create-pull-request-on-change.js
